apiVersion: apps/v1
kind: Deployment
metadata:
  name: mipagina-deployment
spec:
  selector:
   matchLabels:
    app: mipagina
  replicas: 1
  template:
    metadata:
      labels:
        app: mipagina
    spec:
      containers:
        - name: mipagina
          image: ftacurip/nginxft:0.7
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
              name: mipaginaport
        