apiVersion: apps/v1
kind: Deployment
metadata:
  name: ventas-app-back-deployment
spec:
  selector:
   matchLabels:
    app: ventas-app-back
  replicas: 1
  template:
    metadata:
      labels:
        app: ventas-app-back
    spec:
      containers:
        - name: ventas-app-back
          image: dquisiest/spring:0.1
          envFrom:
            - secretRef:
                name: backend-secret
          ports:
            - containerPort: 8080
              name: ventasappbport