#object that store enviroments variables that could be have sensitive data like a password
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  labels:
    app: postgres
    #meant that we can use arbitrary key pair values
type: Opaque
data:
  SPRING_PROFILES_ACTIVE: ZG9ja2Vy
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vMTAuMS4wLjg1OjU0MzIvYmRfcmVnaXN0cm8=
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=
  SPRING_DATASOURCE_PASSWORD: cXdlcnR5