apiVersion: apps/v1
kind: Deployment
metadata:
  name: ventas-app-front-deployment
spec:
  selector:
   matchLabels:
    app: ventas-app-front
  replicas: 1
  template:
    metadata:
      labels:
        app: ventas-app-front
    spec:
      containers:
        - name: ventas-app-front
          image: dquisiest/angular:0.1 
          ports:
            - containerPort: 80
              name: ventasappfport