apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script-configmap
data:
  initdb.sh: |-
   #!/bin/bash
   set -e
   psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ftacurip WITH PASSWORD 'postgres';
    CREATE DATABASE bd_registro;
    GRANT ALL PRIVILEGES ON DATABASE bd_registro TO ftacurip;
   EOSQL